### ISSUE TITLE
Как пользоваться?

### ISSUE THREAD

**Issue by bardimnik** [hikiko4ern/vk_dump#1]
Здравствуйте! А как пользоваться скриптом? Запускал по всякому..., но не пойму что происходит ;-).

З.Ы. По пути /var/mail/ у меня пусто. Использую Ubuntu 16.04.

**Comment by hikiko4ern** [comment]
Здравствуй, @bardimnik!
Скачиваешь архив, распаковываешь, устанавливаешь зависимости (`pip3 install -r requirements.txt`), выполняешь скрипт (`python3 dump.py`), вводишь логин и пароль
![login](https://user-images.githubusercontent.com/25303622/43355299-48a4ba16-9284-11e8-9cde-e7dd0161f4ba.png)
проходит авторизация (может попросить ввести код, если включена двухфакторная аутентификация).

Далее в меню выбираешь, какие данные необходимо сохранить (вводишь цифру и жмёшь Enter)
![dump](https://user-images.githubusercontent.com/25303622/43355419-f32fa27e-9285-11e8-8a29-9b7702bfa52d.png)

Надеюсь, помог :з
