### ISSUE TITLE
Сохранение понравившихся фотографий (отдельно от понравившихся новостей)

### ISSUE THREAD

**Issue by devarped** [hikiko4ern/vk_dump#12]
Как я понимаю, на данный момент утилита может сохранять фотографии из понравившихся постов, в то время, как понравившиеся фотографии отдельно от постов (например, из альбомов или постов с несколькими фотографиями) не сохраняются. 

Проверил это, полностью промотав на одной из страниц соответствующий блок (Новости -> Понравилось -> Понравившиеся фотографии -> Показать все, ранее это была секция "Фотографии" в "Закладках") и посчитав a href, ссылающиеся на фотографии, в исходном коде элемента. Вышло куда большее количество фотографий, чем сохранилось при выборе опции "Данные понравившихся постов" в утилите.

В связи с этим, я прошу добавить возможность сохранения понравившихся фотографий. Насколько я понял, сам список таких фотографий получается API-методом fave.getPhotos.

Заранее спасибо.

**Comment by hikiko4ern** [comment]
Верно, сохранялись вложения только из постов, не учитывая отдельно лайкнутые. Будет сделано :з
